### ISSUE TITLE
2 bug in zspeed.sp

### ISSUE THREAD

**Issue by SKYPIXEL45** [sh4hrazad/sm-some-weird-stuff#1]
1.zspeed的速度显示与jhud有冲突，zspeed.sp Line324中  0.5, iColor[0], iColor[1], iColor[2], 255, 0, 1.0, 0.0, 0.0
                                                                           应改为       0.1, iColor[0], iColor[1], iColor[2], 255, 0, 1.0, 0.0, 0.0  似乎能解决
2. 2d速度与shavittimer hud设置的相反，如果bhoptimer hud选择Use 2D Velocity，zspeed显示的却是3D速度，若关闭Use 2D Velocity，zspeed显示的又是2D速度，将Line300中的  bool bTrueVel = view_as<bool>(Shavit_GetHUDSettings(client) & HUD_2DVEL);
                                                             改为  bool bTrueVel = view_as<bool>((Shavit_GetHUDSettings(client) & HUD_2DVEL) == 0);    似乎能解决

ps: it's a nice plugin!

**Comment by polyarkk** [comment]
> 1.zspeed的速度显示与jhud有冲突，zspeed.sp Line324中 0.5, iColor[0], iColor[1], iColor[2], 255, 0, 1.0, 0.0, 0.0 应改为 0.1, iColor[0], iColor[1], iColor[2], 255, 0, 1.0, 0.0, 0.0 似乎能解决

这样改如果 tick 低一点 HUD 会闪烁（原本我就是这样做的），可以试下：
https://github.com/blankbhop/jhud/blob/cd380c07fdc58f77b74361688ac2cc7cef53b349/jhud.sp#L989
把这行改成
```sourcepawn
	ShowHudText(client, GetDynamicChannel(2), sMessage);
```
前面再加个`#include <DynamicChannels>`
然后重新编译下 jhud.sp ，因为这插件是用 DynamicChannels 来解决 HUD 冲突的，其他没用这插件的可能就会出现这问题。

> 2. 2d速度与shavittimer hud设置的相反，如果bhoptimer hud选择Use 2D Velocity，zspeed显示的却是3D速度，若关闭Use 2D Velocity，zspeed显示的又是2D速度，将Line300中的 bool bTrueVel = view_as(Shavit_GetHUDSettings(client) & HUD_2DVEL); 改为 bool bTrueVel = view_as((Shavit_GetHUDSettings(client) & HUD_2DVEL) == 0); 似乎能解决

这个是我写反了😳，我等下就改

> ps: it's a nice plugin!

thx^_^

**Comment by SKYPIXEL45** [comment]
> 这样改如果 tick 低一点 HUD 会闪烁（原本我就是这样做的），可以试下： https://github.com/blankbhop/jhud/blob/cd380c07fdc58f77b74361688ac2cc7cef53b349/jhud.sp#L989 把这行改成
> 
> ```sourcepawn
> 	ShowHudText(client, GetDynamicChannel(2), sMessage);
> ```
> 
> 前面再加个`#include <DynamicChannels>` 然后重新编译下 jhud.sp ，因为这插件是用 DynamicChannels 来解决 HUD 冲突的，其他没用这插件的可能就会出现这问题。


emmm好像改了以后仍然有冲突， DynamicChannels加过了，插件也改过重新编译了

**Comment by polyarkk** [comment]
[#cbeb6e](https://github.com/sh4hrazad/sm-some-weird-stuff/commit/cbeb6e380cc7fc6e09e7dd7bcb7d84dd299e3b9e)
改好了, 应该不冲突了 (除了 strafetrainer)

**Comment by SKYPIXEL45** [comment]
> [#cbeb6e](https://github.com/sh4hrazad/sm-some-weird-stuff/commit/cbeb6e380cc7fc6e09e7dd7bcb7d84dd299e3b9e) 改好了, 应该不冲突了 (除了 strafetrainer)

刚试了一下用你说的dynamicchannel的方法改了一下strafetrainer发现也没冲突了
https://github.com/PaxPlay/bhop-strafe-trainer/blob/master/scripting/strafe_trainer.sp/#L212
这一行

这样jhud，strafetrainer，zspeed三者互不冲突了耶
